-- Enable pgvector extension for embedding similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Anonymous users (UUID stored in localStorage)
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_token TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habit plans generated by the AI pipeline
CREATE TABLE IF NOT EXISTS habit_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('fitness', 'productivity', 'learning')),
  habit_goal TEXT NOT NULL,
  motivation TEXT,
  constraints JSONB DEFAULT '{}',
  lifestyle_context TEXT,
  conversation_history JSONB DEFAULT '[]',
  generated_plan JSONB,
  psychology_principles TEXT[] DEFAULT '{}',
  confidence_score FLOAT CHECK (confidence_score >= 0 AND confidence_score <= 1),
  difficulty_level TEXT CHECK (difficulty_level IN ('rookie', 'explorer', 'master')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Daily habit tracking entries
CREATE TABLE IF NOT EXISTS habit_tracking (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  plan_id UUID REFERENCES habit_plans(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  notes TEXT,
  xp_earned INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, plan_id, date)
);

-- User gamification state
CREATE TABLE IF NOT EXISTS user_gamification (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  total_xp INT DEFAULT 0,
  current_streak INT DEFAULT 0,
  longest_streak INT DEFAULT 0,
  badges JSONB DEFAULT '[]',
  level TEXT DEFAULT 'rookie' CHECK (level IN ('rookie', 'explorer', 'achiever', 'master', 'legend'))
);

-- Pre-embedded success cases for semantic search
CREATE TABLE IF NOT EXISTS success_cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category TEXT NOT NULL CHECK (category IN ('fitness', 'productivity', 'learning')),
  habit_description TEXT NOT NULL,
  user_profile JSONB DEFAULT '{}',
  success_strategy TEXT NOT NULL,
  key_principles TEXT[] DEFAULT '{}',
  embedding VECTOR(384)
);

-- Index for cosine similarity search on success_cases
CREATE INDEX IF NOT EXISTS success_cases_embedding_idx
  ON success_cases
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 50);

-- Row Level Security (permissive for anonymous MVP — tighten post-MVP)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE habit_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_gamification ENABLE ROW LEVEL SECURITY;
ALTER TABLE success_cases ENABLE ROW LEVEL SECURITY;

-- Allow service role full access (used by API routes with service key)
CREATE POLICY "Service role full access" ON users FOR ALL USING (true);
CREATE POLICY "Service role full access" ON habit_plans FOR ALL USING (true);
CREATE POLICY "Service role full access" ON habit_tracking FOR ALL USING (true);
CREATE POLICY "Service role full access" ON user_gamification FOR ALL USING (true);
CREATE POLICY "Service role full access" ON success_cases FOR ALL USING (true);
